function [net] = NNfit(inputs, targets)
% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by NFTOOL
%
% This script assumes these variables are defined:
%
 
% Create a Fitting Network
hiddenLayerSize = 4;
net = fitnet(hiddenLayerSize);

% Set up Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;
 
% Train the Network
[net,tr] = train(net,inputs,targets);
 
% Test the Network
outputs = net(inputs);
errors = gsubtract(outputs,targets);
performance = perform(net,targets,outputs)
 
% View the Network
%view(net)
 
% Plots
% Uncomment these lines to enable various plots.
  figure, plotperform(tr)
%  figure, plottrainstate(tr)
%   figure, plotfit(targets,outputs)
 figure, plotregression(targets,outputs)
 figure, ploterrhist(errors)
